---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/andrekloster/argo-test.git
    targetRevision: main
    path: kubernetes/apps/external-dns

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
